library(here)
library(adnuts)
library(ggplot2)
library(RColorBrewer)
library(doBy)
library(tidyr)
library(dplyr)
library(gridExtra)
library(tidyverse)
library(purrr)
library(stringr)
library(ggplot2)
library(knitr)
library(kableExtra)
options(knitr.kable.NA = '')
knitr::opts_knit$set(root.dir = '../../' )
library(captioner)
library(bibtex)
library(knitcitations)
library(cowplot)
library(magick)
library(bookdown)
library(ggthemes)
library(ggridges)
source(("read-admb.R"))
source(("plot-age-comps.R"))
source(("plot_sex_ratio.R"))
source(("get_like_table.R"))
source(("plot_sel.R"))
source(("plot_srv_sel.R"))
source("compareRuns.r")
source(("plot_ssb.R"))
source(("plot_fut_Fs.R"))
source(("plot_rec.R"))
source(("plot_bts.R"))
source(("plot_q.R"))
source(("plot_srr.R"))
source(("plot_catch.R"))

.THEME <- theme(panel.grid.major.x = element_blank(), panel.grid.minor.y = element_blank(), panel.grid.major.y = element_blank() )
.THEME <- .THEME + theme(text=element_text(size=18)) + theme(axis.title.x=element_text(size=24) ,axis.title.y=element_text(size=24))
.THEME <- .THEME + theme(panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(),panel.grid.minor.y = element_line(colour="grey60", linetype="dashed"), panel.grid.major.y = element_blank() )
.THEME <- .THEME + theme( panel.background = element_rect(fill="white"), panel.border = element_rect(colour="black", fill=NA, size=1))
.OVERLAY <- TRUE
