#  Executive summary

This chapter covers the Eastern Bering Sea (EBS) region—the Aleutian Islands
region (Chapter 1A) and the Bogoslof Island area (Chapter 1B) are presented
separately.

### Summary of changes in assessment inputs
1)  2017 fishery age composition.
2)  2017 survey age composition.
3)  2018 trawl survey biomass point estimate and standard error.
4)  Estimate of the discarded and retained portions of the 2017 catch.
5)  Estimate of total catch made through the end of 2018. Catch of 150,000 t assumed for 2019 and 2020 projection. 


#### Changes in the data

   1.	The 2018 NMFS bottom-trawl survey (BTS) biomass and abundance at age estimates were included. 

   2.  The 2018 NMFS acoustic-trawl survey (ATS) biomass and abundance were
   included (using mainly samples from the BTS survey for age-length keys)

   2.  The 2018 opportunistic acoustic data from vessels (AVO) conducting the
   bottom trawl survey was used as an added index of pollock biomass in mid-
   water. 

   2.  Observer data for catch-at-age and average weight-at-age from
   the 2016 fishery were finalized and included. 

   2.  Total catch as reported by NMFS Alaska Regional office was updated and included through `r thisyr`.

### Changes in the assessment methods

Explored incorporating survey start date and its interaction term with annual
bottom water temperature in the survey catchability equation.  


## Summary of BSAI yellowfin sole results

The assessment updates last year’s with results and management quantities that
are lower than the 2017 assessment primarily due to 1) the 2018 survey biomass
point estimate is 32% lower than the 2017 estimate and 2) the assessment model
estimated a slightly lower survey catchability.  Yellowfin sole continue to be
well-above BMSY and the annual harvest remains below the ABC level.  The
female spawning stock is in a slow downward trend.  Management quantities are
given below for the current base model (Model 14_1) and a new base model

\begin{table}[ht]
\centering
\begin{tabular}{lrr|rr}
  \hline
       & \multicolumn{2}{c|}{As estimated or $\mathit{specified}$ } & \multicolumn{2}{c}{As estimated or $\mathit{recommended}$ }  \\
       & \multicolumn{2}{c|}{$\mathit{last}$ year for:}  & \multicolumn{2}{c}{$\mathit{this}$ year for: }               \\
        Quantity & `r thisyr`      &`r thisyr+1`   & `r thisyr+1`      &`r thisyr+2` \\ 
  \hline
	M (natural mortality rate, ages 3+)	&	0.3	&	0.3	&	0.3	&	0.3 \\
Tier	&	1a	&	1a	&	1a	&	1a \\
Projected total (age 3+) biomass (t)	&10,965,000 t & 10,117,000 t &	`r M$age3plus1s` t	   &	`r M$age3plus2s` t  \\
Projected female spawning biomass (t) &	3,678,000 t	&	3,365,000 t	&		`r M$ssb1s` t	         &	`r M$ssb2s` t	      \\
$B_0$                                 &	5,394,000 t	&	5,394,000 t	&		`r M$b0s`,000 t	       &	`r M$b0s`,000 t	    \\
$B_{msy}$                             &	2,042,000 t	&	2,042,000 t	&		`r M$bmsys`,000 t	     &	`r M$bmsys`,000 t	  \\
$F_{OFL}$                             &	0.621	      &	0.621	      &		`r round(M$arithmeanF,3)`	   &	`r round(M$arithmeanF,3)`	\\
$maxF_{ABC}$                          & 0.466	      &	0.466	      &	  `r round(M$harmeanF,3)`	     &	`r round(M$harmeanF,3)`  	\\
$F_{ABC}$                             &	0.336       &	0.336       &		`r (M$fabc1s)`           &	`r (M$fabc2s)`        \\
$OFL$    	                            &	4,797,000 t	&	4,592,000 t	&	  `r M$ofl1s` t          &	`r M$ofl2s` t       \\
$maxABC$    	                        &	3,603,000 t	&	3,448,000 t	&		`r M$maxabc1s ` t      &	`r M$maxabc2s ` t   \\
$ABC$ 	                             &	2,592,000 t	&	2,467,000 t	&		`r M$abc1s ` t         &	`r M$abc2s` t       \\
\hline
Status	                              &	2016	      &	2017	      &		`r lastyr`             &	`r thisyr`          \\
\hline
Overfishing	                          &	No	        &	n/a	      &	No	                       &	n/a                 \\
Overfished	                          &	n/a	        &	No	      &	n/a	                       &	No                  \\
Approaching overfished	              &	n/a	        &	No	      &	n/a	                       &	No                  \\
\hline
\end{tabular}
\end{table}

## Response to SSC and Plan Team comments

### General comments 

In this section, we list new or outstanding comments on assessments in general
from the last full assessment in 2017. 

_“The SSC recommends that, for those sets of environmental and fisheries observations that support the inference of an impending severe decline in stock biomass, the issue of concern be brought to the SSC, with an integrated analysis of the indices in future stock assessment cycles. To be of greatest value, to the extent possible, this information should be presented at the October Council meeting so that there is sufficient time for the Plan Teams and industry to react to the possible reduction in fishing opportunity.” (SSC October 2017)_

To facilitate a coordinated response to this request, the co-chairs and
coordinators of the BSAI and GOA Groundfish Plan Teams, with concurrence from
stock assessment program leadership at the AFSC, have suggested that authors
address it by using the previous year’s Ecosystem Status Report (ESR) as
follows:

_“No later than the summer of each year, the lead author of each assessment
should review the previous year’s ESR and determine whether any factor or
set of factors described in that ESR implies an impending severe decline in
stock/complex biomass, where “severe decline” means a decline of at least
20% (or any alternative value that may be established by the SSC), and where
biomass is measured as spawning biomass for Tiers 1-3 and survey biomass as
smoothed by the standard Tier 5 random effects model for Tiers 4-5. If an
author determines that an impending severe decline is likely and if that
decline was not anticipated in the most recent stock assessment, he or she
should summarize that evidence in a document that will be reviewed by the
respective Team in September of that year and by the SSC in October of that
year, including a description of at least one plausible mechanism linking
the factor or set of factors to an impending severe decline in biomass, and
also including an estimate or range of estimates regarding likely impacts on
ABC. In the event that new survey or relevant ESR data become available
after the document is produced but prior to the October Council meeting of
that year, the document should be amended to include those data prior to its
review by the SSC, and the degree to which they corroborate or refute the
predicted severe decline should be noted, with the estimate or range of
estimates regarding likely impacts on ABC modified in light of the new data
as necessary.”_

_Stock assessment authors are encouraged to work with ESR analysts to identify
a small subset of indicators prior to analysis, and preferably based on
mechanistic hypotheses.” (SSC October 2018)_

It has been demonstrated that annual bottom water temperature is at least a partial determinate of yellowfin sole late spring/summertime distribution.  However it is unclear how temperature is related to the productivity of the stock.  This species does not rely on ocean/atmosphere advective properties but instead migrates directly to nursery areas to spawn, so may be more resilient to changing ocean conditions.  We also know that somatic growth is positively related to bottom temperature that may result in increased fecundity.  Stock assessment authors would welcome the chance to work with an ESR analysist to think about indicators.

_The SSC also recommends explicit consideration and documentation of ecosystem
and stock assessment status for each stock ... during the December Council
meeting to aid in identifying stocks of concern.” (SSC October 2017)_

Clarification during December 2017 SSC meeting and then re-clarified during June 2018 SSC meeting. In the interest of efficiency, the clarification from the December 2017 minutes is not included here. The relevant portion of the clarification from the June 2018 minutes reads as follows:
“This request was recently clarified by the SSC by replacing the terms ‘ecosystem status’ and ‘stock assessment status’ with ‘Ecosystem Status Report information’ and ‘Stock Assessment Information,’ where the potential determinations for each will consist of ‘Okay’ and ‘Not Okay,’ and by issuing the following guidance:
• The SSC clarifies that ‘stock assessment status’ is a fundamental requirement of the SAFEs and is not really very useful to this exercise, because virtually all stocks are never overfished nor is overfishing occurring.
• Rather the SSC suggests that recent trends in recruitment and stock abundance could indicate warning signs well before a critical official status determination is reached. It may also be useful to consider some sort of ratio of how close a stock is to a limit or target reference point (e.g., B/B35). Thus, additional results for the stock assessments will need to be considered to make the ‘Okay’ or ‘Not Okay’ determinations.
• The SSC retracts its previous request for development of an ecosystem status for each stock/complex. Instead, while considering ecosystem status report information, it may be useful to attempt to develop thresholds for action concerning broad-scale ecosystem changes that are likely to impact multiple stocks/complexes.
• Implementation of these stock and ecosystem determinations will be an iterative process and will require a dialogue between the stock assessment authors, Plan Teams, ecosystem modelers, ESR editors, and the SSC.”
“The Teams recommend that the terms ‘current and future ecosystem condition’ and ‘current and future stock condition’ be used in place of ‘ESR information’ and ‘stock assessment information’.” (Plan Team September 2018)
“The SSC recognized that because formal criteria for these categorizations have not been developed by the PT, they will not be presented in December 2018.” (SSC October 2018)
The iterative process described in the final bullet above was scheduled to begin at the September 2018 meeting of the Joint BSAI and GOA Plan Teams. However, no formal criteria for these categorizations were developed by the Plan Teams in September 2018. As specified by the SSC in October, we will not provide determinations for yellowfin sole at this time and will provide determinations when formal criteria are established. 
“The Team recommended that the authors simply report in words or a table whether catches exceed ABC as an indicator for “partial update” stocks. (Plan Team November 2017)
Does not apply to yellowfin sole SAFE report since it is not a “partial update stock”.
“The SSC reminds authors of the need to balance the desire to improve model fit with increased risk of model misspecification.” (SSC December 2017)
Clarification: “In the absence of strict objective guidelines, the SSC recommends that thorough documentation of model evaluation and the logical basis for changes in model complexity be provided in all cases.” (SSC June 2018)
Important point as the 2018 yellowfin sole assessment has increased the number of parameters estimated by 2 to improve fit to survey biomass.  Hopefully our model evaluation is sound by providing a mechanism for the increased complexity from a new paper on availability/temperature correlations.
 “Report a consistent metric (or set of metrics) to describe fish condition among assessments and ecosystem documents where possible.” (SSC December 2017)
We do not yet report fish condition for yellowfin sole. However, if we do report this metric in the future then we will be consistent with the weight-length residual approach to report fish condition as described in the Ecosystem Status Report. 
“Projections ... clearly illustrate the lack of uncertainty propagation in the ‘proj’ program used by assessment authors. The SSC encourages authors to investigate alternative methods for projection that incorporate uncertainty in model parameters in addition to recruitment deviations. Further, the SSC noted that projections made on the basis of fishing mortality rates (Fs) only will tend to underestimate the uncertainty (and perhaps introduce bias if the population distribution is skewed). Instead, a two-stage approach that first includes a projection using F to find the catch associated with that F and then a second projection using that fixed catch may produce differing results that may warrant consideration.” (SSC December 2017)
Please see model evaluation section for alternative Tier 1 projection with uncertainty in F.
“The Teams recommend that the appropriate use, or non-use, of new model based estimates in this assessment cycle be left to individual authors’ discretion. The Teams further recommend that, if an author chooses to incorporate these into the assessment, the assessment should also contain appropriate comparative models and a full set of diagnostics.” (Plan Team September 2018) 
“The SSC supports the PT recommendation to make the use of model-based survey estimates at the individual author’s discretion for 2018.” (SSC October 2018)
This assessment did not utilize any model based survey estimates. In the future, model-based estimates produced by the Groundfish Assessment Program (GAP) will be used to fit the assessment model as a contrast to the current use of survey estimates. A working group was formed to investigate criteria for use of the model-based estimates in a variety of groundfish life histories. We will consult the guidelines from this working group for determining the usefulness of the model-based estimates for yellowfin sole when they become available. 
“The SSC also noted that, in order to save resources, authors should not conduct additional assessments beyond the prioritized schedule unless they specifically trigger one or more of the criteria identified.” (SSC October 2018)
Yellowfin sole is a Tier 1 stock assessment conducted every year and as such it’s frequency for completion is not determined by a specific external criteria.


### Comments specific to this assessment
SSC and Plan Team 2017 minutes:


_The Team recommends plotting the estimated spawning biomass trajectory with a
fixed pair of M and q values that reduces the retrospective pattern (e.g.,
M=0.09 and q=1.0) on top of the estimated spawning biomass trajectory, with
confidence intervals, from the base model run. This comparison will help to
determine if the different combination of M and q values is within the
estimated uncertainty of the base model, or is describing a completely
different population size._

Please see Retrospective Analysis section of this report.
 The M=0.09 and q=1.0 retrospective model runs are outside the confidence intervals of the assessment model spawning biomass trajectory for about a 17 year period from 1978-1995.  Otherwise it is generally within the uncertainty of the assessment model results.
The Team recommends continuing to explore the retrospective patterns in relation to values of M and q, with fixed values of M and fixed values of q, reporting values of Mohn’s rho for each combination (range to be decided by the authors). Additionally, using those same model runs, report the total likelihood for each combination to create a bivariate likelihood profile for those parameters. Realizing that this will require a considerable number of model runs, the Team leaves it up to the authors to decide whether using the model runs done for the 2017 assessment will suffice, or if important differences arise from a 2018 model that warrant redoing those model runs.
One ongoing concern with the assessment is a strong retrospective pattern in female spawning biomass, whereby more recent assessments tend to yield higher biomass estimates (Figure 4.21). Pursuant to requests by the Plan Team and SSC, the authors explored the effects of M and q on these patterns. Lower values of q and M resulted in better retrospective patterns and lower Mohn’s test statistics. The SSC supports the Plan Team’s recommendation to select a parameterization (e.g., M=0.09 and q=1.0) that reduces the retrospective pattern and to determine whether spawning biomass projections from this parameterization fall within the uncertainty of the base model or if it describes different population trends. The SSC also endorses the Plan Team’s recommendation to continue to explore effects of M and q on the retrospective patterns in biomass. 
The M-q analysis of 2017 was repeated in 2018 but focused on the pattern of model fit (-log likelihood) instead of Mohn’s test statistic and indicated that the best fit to the stock assessment model occurs at M and q values higher than where the best retrospective pattern occurs.  
The SSC notes that potential improved performance of the model with lower values of M are interesting, given that M appears to have been well specified both outside the model (based on multiple methods of estimation, including analysis of old Japanese pair trawl effort data) as well as inside the model (profile of M over a range of values). A natural mortality value of 0.12 is used for both sexes in the base model. Pending the outcome of efforts to explore effects of M and q on the retrospective pattern, the SSC recommends that the authors reexamine alternative methods and data available to estimate M independent of the model in attempts to independently “validate” the plausibility of the results. 
Natural mortality modeling was not attempted in 2018 but can be done in 2019, for both sex-specific M and also time-varying M.
The SSC notes that there appears to be a strong time trend in the proportion of fish in the final age bin (age 17+) in the fishery catch at age data for both males and females (Table 4.4). Prior to 1980, there were no fish in this category. This proportion has generally increased from the mid 1980s to a maximum of 19% for males in 2004 and 23% for females in 1999, and fluctuated at relatively high levels through 2016. Such a pattern could be consistent with time-varying M, although there may be other explanations. For next year’s assessment, the SSC recommends that the assessment authors consider the evidence for time-varying M and evaluate the ability of time-varying M to address the retrospective biomass pattern in an alternative model.
The pattern of increasing proportion of fish in the plus group for our time-series can also be explained by overfishing the stock in the early 1960s by foreign fleets where the yellowfin sole stock was reduced to very low levels and the larger fish were mostly gone.  By 1980 the age 15+ fish were beginning to accumulate in the population again and increased thereafter (to the present) with more prudent management.


# Introduction

## General

The yellowfin sole (_Limanda aspera_) is one of the most abundant flatfish
species in the eastern Bering Sea (EBS) and currently is the target of the
largest flatfish fishery in the world.  They inhabit the EBS shelf and are
considered one stock.  Abundance in the Aleutian Islands region is negligible.

Yellowfin sole are distributed in North American waters from off British
Columbia, Canada, (approx. lat. 49o N) to the Chukchi Sea (about lat. 70o N)
and south along the Asian coast off the South Korean coast in the Sea of Japan
(to about lat. 35o N).  Adults exhibit a benthic lifestyle and occupy separate
winter, spawning and summertime feeding distributions on the eastern Bering
Sea shelf.  From over-winter grounds near the shelf margins, adults begin a
migration onto the inner shelf in April or early May each year for spawning
and feeding.  The directed fishery historically occurred from winter through
autumn (Wilderbuer et al. 1992).  Yellowfin sole are managed as a single stock
in the BSAI management area as there is presently no evidence of stock
structure.
 

## Review of Life History 

In the EBS pollock spawn generally in the period
March-May and in relatively localized regions during specific periods (Bailey
2000). Generally spawning begins nearshore north of Unimak Island in March and
April and later near the Pribilof Islands (Jung et al. 2006, Bacheler et al.
2010). Females are batch spawners with up to 10 batches of eggs per female per
year. Eggs and larvae of EBS pollock are planktonic for a period of about 90
days and appear to be sensitive to environmental conditions. These conditions
likely affect their dispersal into favorable areas (for subsequent separation
from predators) and also affect general food requirements for over-wintering
survival (Gann et al. 2015, Heintz et al., 2013, Hunt et al. 2011, 
Ciannelli et al. 2004). Duffy-Anderson et al. (2015) provide a
review of the early life history of EBS pollock.

Throughout their range juvenile pollock feed on a variety of planktonic
crustaceans,  including calanoid copepods and euphausiids. In the EBS shelf
region, one-year-old pollock are found throughout the water column, but also
commonly occur in the NMFS bottom trawl survey. Ages 2 and 3 year old pollock
are rarely caught in summer bottom trawl survey gear and are more common in
the  midwater zone as detected by mid-water acoustic trawl surveys. Younger
pollock are  generally found in the more northern parts of the survey area and
appear to move to the southeast as they age (Buckley et al. 2009).
Euphausiids, principally _Thysanoessa inermis_ and _T. raschii_, are among the
most important prey items for pollock in the Bering Sea (Livingston, 1991;
Lang et al., 2000; Brodeur et al., 2002; Cianelli et al., 2004; Lang et al.,
2005).  Pollock diets become more piscivorous with age, and cannibalism has
been commonly observed in this region. However, Buckley et al. (2016) showed
spatial patterns of pollock foraging by size of predators. For example, the
northern part of the the shelf region between the 100 and 200 m isobaths
(closest to the shelf break) tends to be more piscivorous than counterparts in
other areas.


## Stock structure

Data from the survey work in the Northern Bering Sea (NBS) region (north of
Nunivak Island to the Russian convention line and into Norton Sound) from 2017
and 2018, as shown below and evaluated in the appendix, suggests that there
are concentrations of pollock present which contrasts with the 2010 survey
when relatively few pollock were present. The pattern of temperatures in the
region likely affect the pollock distribution in ways that likely vary over
time.  However, there is evidence of a relationship between mean bottom
temperatures in the US zone on the EBS shelf and subsequent biomass estimates
in the  Navarin basin (the Russian area adjacent to the Convention Line; e.g.,
Stepanenko and Gritsay 2018,  Ianelli et al. 2015). Some genetic samples were
taken from pollock and collections continue. Pending funding availability,
analysis of these samples could  help ascertain the extent that these fish are
related to those observed in the normal EBS shelf survey area.   Genetic
samples taken from the 2017 summer bottom trawl survey from the Northern
Bering Sea can be compared with samples from the standard Bering Sea Unimak,
Pribilof, Bogoslof, and Zhemchug. This planned study should help improve stock
structure evaluation (last done in Ianelli et al. 2015).


# Fishery  
## Description of the directed fishery 

Yellowfin sole have annually been caught with bottom trawls on the Bering Sea shelf since the fishery began in 1954 and were overexploited by foreign fisheries in 1959-62 when catches averaged 404,000 t annually (Fig. 4.1, top panel).  As a result of reduced stock abundance, catches declined to an annual average of 117,800 t from 1963-71 and further declined to an annual average of 50,700 t from 1972-77.  The lower yield in this latter period was partially due to the discontinuation of the U.S.S.R. fishery.  In the early 1980s, after the stock condition had improved, catches again increased reaching a peak of over 227,000 t in 1985.  

During the 1980s, there was also a major transition in the characteristics of the fishery.  Yellowfin sole were traditionally taken exclusively by foreign fisheries and these fisheries continued to dominate through 1984.  However, U.S. fisheries developed rapidly during the 1980s in the form of joint ventures, and during the last half of the decade began to dominate and then take all of the catch as the foreign fisheries were phased out of the EBS.  Since 1990, only domestic harvesting and processing has occurred.  

The management of the yellowfin sole fishery changed significantly in 2008 with the implementation of Amendment 80 to the BSAI Fisheries Management Plan.  The Amendment directly allocated fishery resources among BSAI trawl harvesters in consideration of their historic harvest patterns and future harvest needs in order to improve retention and utilization of fishery resources by the non-AFA trawl catcher/processor fleet.  This was accomplished by extending the groundfish retention standards to all H&G vessels and also by providing the ability to form cooperatives within the newly formed Amendment 80 sector.  In addition, Amendment 80 also mandated additional monitoring requirements which included observer coverage on all hauls, motion-compensating scales for weighing samples, flow scales to obtain accurate catch weight estimates for the entire catch, no mixing of hauls and no on-deck sorting.  The partitioning of TAC and PSC (prohibited species catch) among cooperatives has significantly changed the way the annual catch has accumulated (Fig 4.1, bottom panel) and the rate of target catch per bycatch ton. There is now a more even and slow attainment of the annual catch relative to the pre-Amendment 80 fishing behavior.  

Yellowfin sole are usually headed and gutted, frozen at sea, and then shipped to Asian countries for further processing (AFSC 2016).  The first wholesale value of Alaska yellowfin sole totaled $97.8 million in 2014.  From 2016 to 2017 the first wholesale price of all Bering Sea flatfish fisheries increased 16% to $192.9 million t and yellowfin sole price increased 19% year over year. In 2010, following a compr,ehensive assessment process, the yellowfin sole fishery was certified under the Marine Stewardship Council environmental standard for sustainable and well-managed fisheries.  The certification also applies to all the major flatfish fisheries in the BSAI and GOA.  The total annual catch (t) since implementation of the MFCMA in 1977 is shown in Table 4.1.

In 2011, federally permitted vessels using non-pelagic trawl gear whose harvest results in flatfish retained catch that is greater than any other retained fishery category were required to use modified trawl gear.  The modifications required the use of elevating devices to raise the section of the trawl warps between the doors and the trawl wing tips by 2.5 inches off the seafloor.  The purpose of the management action was to reduce damage of non-target animals, particularly those that form habitat structure or support other fisheries while not substantially reducing flatfish catch rates or causing gear handling problems (Rose et al. 2010).

The 1997 catch of 181,389 t (retained and discards) was the largest since the fishery became completely domestic but was at lower levels from 1998–2010, averaging 94,004 t (Table 4.2).  From 2011-2014 the catch increased, averaging 155,000 t.  The 2013 catch totaled 165,000 t (73% of the ABC), the highest annual catch in the past 19 years.  For 2018, the catch distribution has been spread out from January through May with the majority coming from 4 BSAI management areas (509, 513, 514, 517).  As of mid-September 2018, the fishing season is ongoing.  In order to estimate the total 2018 catch for the stock assessment model, the average proportion of the 2010-2017 cumulative catch attained by the 35th week of the year (mid-September) was applied to the 2018 catch amount at the same time period and results in a 2018 catch estimate of 146,500 t (53% of the ABC).  The size composition of the 2018 catch for both males and females, from observer sampling, are shown in Figure 4.2, the catch proportions by month and area are shown in Figure 4.3, and maps of the locations where yellowfin sole were caught in 2018, by month (through mid-September), are shown in Figure 4.4.  The average age of yellowfin sole in the 2017 catch is estimated at 12.6 and 13.5 years for females and males, respectively.

The time-series of catch in Table 4.1 also includes yellowfin sole that were discarded in domestic fisheries from 1987 to the present.  Annual discard estimates were calculated from at-sea sampling (Table 4.2).  The rate of discard has ranged from a low of 2% of the total catch in 2012 (and 2015) to 30% in 1992 and is estimated at 3% in the 2017 fishery.  The trend has been toward fuller retention of the catch in recent years, and with the advent of the Amendment 80 harvest practices, discarding is at its lowest level since these estimates have become available.  Historically, discarding primarily occurred in the yellowfin sole directed fishery, with lesser amounts in the Pacific cod, Pollock, rock sole, flathead sole, and “other flatfish” fisheries (Table 4.3).



### Catch patterns

The \"A-season\" for directed EBS pollock ...





## Management measures

The EBS pollock stock is managed by NMFS...








## Economic conditions as of 2017

Alaska pollock is the dominant species in terms of catch in the Bering Sea \&



# Data

The following lists the data used in this assessment: 

\begin{table}[ht]
\centering
\label{tab:dataextent}
\begin{tabular}{p{1.5in}p{1.8in}p{2.8in}}
\hline
 Source & Type & Years \\
\hline
 Fishery & Catch biomass & 1964--`r thisyr` \\
 Fishery & Catch age composition & 1964--`r lastyr` \\
 Fishery & Japanese trawl CPUE & 1965--1976 \\
 EBS bottom trawl & Area-swept biomass and age-specific proportions & 1982--`r thisyr` \\
 Acoustic trawl survey & Biomass index and age-specific proportions & 1994, 1996, 1997, 1999, 2000, 2002, 2004, 2006--2010, 2012, 2014, 2016, 2018 \\
 Acoustic vessels of opportunity (AVO) & Biomass index & 2006--`r thisyr` \\
\hline
\end{tabular}
\end{table}

## Fishery 
### Catch

This assessment uses fishery catch data from 1955- 2018 (shown for 1964-2018
in Table 4.1), including an estimate of the 2018 catch, and fishery
catch-at-age (proportions) from 1964-2017 (Table 4.4, 1975-2017).  The 2017
fishery age composition was primarily composed of fish older than 9 years with
a large amount of 20+ fish.

## Surveys

### Bottom trawl survey (BTS)

Indices of relative abundance available from AFSC surveys have shown a major
increase in the abundance of yellowfin sole during the late 1970s, increasing
from 21 kg/ha in 1975 to 51 kg/ha in 1981 (Fig. 4.2 in Bakkala and Wilderbuer
1990).  These increases have also been documented through Japanese commercial
pair trawl data and catch-at-age modeling in past assessments (Bakkala and
Wilderbuer 1990).

Since 1981, the survey CPUEs have fluctuated widely (Fig. 4.5).  Biomass
estimates for yellowfin sole from the annual bottom trawl survey on the
eastern Bering Sea shelf are shown in Table 4.5 and Figure 4.6.  The data show
a doubling of survey biomass between 1975 and 1979 with a further increase to
over 3.3 million t in 1981.  Total survey abundance estimates fluctuated
erratically from 1983 to 1990 with biomass ranging from as high as 3.5 million
t in 1983 to as low as 1.9 million t in 1986. Biomass estimates since 1990
indicate an even trend at high levels of abundance for yellowfin sole, with
the exception of the results from the 1999 and 2000 summer surveys, which were
at lower levels.  Surveys from 2001-2005 estimated an increase each year but
the estimates since 2006 indicate a stable level with some annual variability.
 However, the 2012 estimate is a 19% decrease from 2011 and the 2013 and 2014
surveys have estimated a 17% increase over 2012.  Similarly, there was a 24%
decrease from 2014 to 2015 followed by a 48% increase from 2015 to 2016, the
highest biomass estimate since 1984. Fluctuations of the magnitude shown
between 1980 and 1990, 1998 and 1999, 2008 and 2009, 2011and 2012,  2014 and
2015 and 2015 and 2016 are unreasonable considering the elements of slow
growth and long life span of yellowfin sole combined with low to moderate
exploitation rate, characteristics which should produce more gradual changes
in abundance.

Variability of yellowfin sole survey biomass estimates (Fig. 4.6) is in part
due to the availability of yellowfin sole to the survey area (Nichol 1998). 
Yellowfin sole are known to undergo annual migrations from wintering areas off
the shelf-slope break to near shore waters where they spawn throughout the
spring and summer months (Nichol, 1995; Wakabayashi, 1989; Wilderbuer et al.,
1992).  Exploratory survey sampling in coastal waters of the eastern Bering
Sea during early summer indicate that yellowfin sole concentrations can be
greater in these shallower areas not covered by the standard AFSC survey than
in the survey proper.  Commercial bottom trawlers have commonly found high
concentrations of yellowfin sole in areas such as near Togiak Bay (Low and
Narita, 1990) and in more recent years from Kuskokwim Bay to just south of
Nunivak Island.  The coastal areas are sufficiently large enough to offer a
substantial refuge for yellowfin sole from the current survey.  

Over the past 18 years, survey biomass estimates for yellowfin sole have shown
a positive correlation with shelf bottom temperatures (Nichol, 1998);
estimates have generally been lower during cold years.   The 1999 survey,
which was conducted in exceptionally cold waters, indicated a decline in
biomass that was unrealistic.  The bottom temperatures during the 2000 survey
were much warmer than in 1999, and the biomass increased, but still did not
approach estimates from earlier years.  Average bottom temperature and biomass
both increased again during the period 2001 – 2003, with the 2003 value the
highest temperature and biomass observed over the 22 year time series up to
that time.  Given that both the 1999 and 2000 surveys were conducted two weeks
earlier than previous surveys, it is possible that the time difference may
also have also affected the availability of yellowfin sole to the survey.  If,
for example, the timing of peak yellowfin sole spawning in nearshore waters
corresponded to the time of the survey, a greater proportion of the population
would be unavailable to the standard survey area.  This pattern was observed
again in 2009 and 2012 when the temperatures and the bottom trawl survey point
estimates were lower.  Summer shelf bottom temperatures in 2012 were the 2nd
coldest recorded by the survey and the time-series and resulted in a 19%
decline from 2011.  In 2016 the Bering Sea had the highest recorded bottom
temperature since measurements began in 1982 and the 2016 estimate of biomass
was the highest in 32 years and 48% higher than the 2015 estimate.  The 2017
survey estimate of 2,787,700 t was 3% lower than 2016, but the 2018 estimate
of 1,892,925 (another warm year) was down 32% from 2017.

We propose two possible reasons why survey biomass estimates are lower during
years when bottom temperatures are low.  First, catchability may be lower
because yellowfin sole may be less active when cold.  Less active fish may be
less susceptible to herding, and escapement under the footrope of survey gear
may increase if fish are less active.  Secondly, bottom temperatures may
influence the timing of the inshore spawning migrations of yellowfin sole and
therefore affect their availability to the survey area (Nichol et al. in
review).  Because yellowfin sole spawning grounds include nearshore areas
outside the survey area, availability of fish within the survey area can vary
with the timing of this migration and the timing of the survey.  In the case
of 2016, a very warm year in the Bering Sea, it appears that a higher portion
of the adult biomass was distributed on the shelf (outside of the spawning
areas) relative to the average of all previous survey years, indicating
earlier spawning migration (Fig 4.7).  

Yellowfin sole population numbers-at-age estimated from the annual bottom
trawl surveys are shown in Table 4.6 and their occurrence in trawl survey
hauls and associated collections of lengths and age structures since 1982 are
shown in Table 4.7.  Their total tonnage caught in the resource assessment
surveys since 1982 are listed in Table 4.8 and also in an appendix table with
IPHC survey catches.

### Northern Bering Sea survey

Trawl survey sampling was extended to the northern Bering Sea in 2010, 2017
and 2018.  The trawl surveys conducted in 2010 and 2017 occupied the same
areas with similar sampling densities.  The 2018 survey was a reduced effort
and only sampled a subset of the northern Bering Sea.  Stations in 2018 were
30 nautical miles apart (instead of 20 nm) and excluded Norton Sound and
inshore areas north of Nunivak Island.  For comparison among years (2010,
2017, 2018), biomass estimates were derived by truncating the areal coverage
of the 2010 and 2017 surveys to include only the area covered in 2018 that was
common to all three surveys, and this was treated as a single stratum (Table
4.5).   This truncated area is 158,286 square kilometers (compared to 200,207
square kilometers in 2010 & 2017).  There was a small increase in the estimate
of yellowfin sole in the truncated survey area from the 3 surveys. Since
yellowfin sole fishing is presently prohibited in the northern Bering Sea, the
biomass from this area is not included in the stock assessment model.

###  Age Determination

Yellowfin sole ages have been determined at the AFSC by using the break and burn method on otoliths collected in surveys and from fisheries since 1979.  In 2016 the age determination methods for yellowfin sole were validated using the bomb-produced uptake measurement of 14C method (Kastelle et al. 2016).

### Length and Weight-at-Age 

Past assessments of yellowfin sole have used sex-specific, time-invariant
growth based on the average length-at-age and weight-at-length relationships
from the time-series of survey observations summed over all years since 1982. 
These weight-at-age estimates were estimated from the following relationships:

Parameters of the von Bertalanffy growth curve have been estimated for
yellowfin sole, by sex, from the trawl survey database as follows: 

                                                              Linf               K            t0                       n
                                 Males                   33.7           0.161      -0.111       656
                       Females               37.8           0.137        0.112       709

A sex-specific length-weight relationship was also calculated from the survey
database using the usual power function, weight (g) =  a Length(cm)b, where a
and b are parameters estimated to provide the best fit to the data (Fig. 4.8).
 

                                                         a                    b                      n
                                      males      0.00854         3.081               2,701
                                      females   0.0054           3.227               3,662

These estimates of weight at length were applied to the annual trawl survey
estimates of population length at age, by sex, to calculate the weight at each
age (Fig. 4.8).  Since the resulting estimates of annual weight-at-age were
highly variable for fish older than 11 years, ages 11-20 were smoothed using a
five year average smoothing method for 1982-2018.

Applications of dendrochronology (tree-ring techniques) have been used to
develop biochronologies from the otolith growth increments of northern rock
sole (Lepidopsetta polyxystra), yellowfin sole and Alaska plaice (Pleuronectes
quadrituberculatus) in the eastern Bering Sea. These techniques ensure that
all growth increments are assigned the correct calendar year, allowing for
estimation of somatic growth by age and year for chronologies that span
approximately 25 years (Matta et al. 2010).  The analysis indicated that
yellowfin sole somatic growth exhibits annual variability and has a strong
positive correlation with May bottom water temperature in the Bering Sea (Fig.
4.9).

The relationship between temperature and growth was further explored by
reanalyzing yellowfin sole growth by age and year.  Length-weight data
collected when obtaining otolith (age) samples in RACE surveys (n=7,000 from
1987, 1994 and 1999-2009) also indicate that weight at age exhibits annual
variability and is highly correlated with summer bottom water temperature
observations with a lag of 2-3 years for the temperature effect to be seen
(shown for age 5 fish in figure 4.10) .  These observations were then extended
back to 1979 using survey population length-at-age estimates (since
weight-at-age is a power function of the length-at-age, Clark et al. 1999,
Walters and Wilderbuer 2000).  

In order to incorporate time-varying (year effect on growth) and
temperature-dependent growth functions into the age-structured stock
assessment model we used the annual observed population mean weight-at-age
(time-varying) from the trawl survey. These empirical data indicate good
somatic growth correspondence with annual bottom temperature anomalies from
1982-2017 (Fig. 4.11).  Fishery weight at age data available from 2008-2016
were averaged across years for each age to provide updated estimates for the
fishery 

### Maturity-at-age

Maturity information collected from yellowfin sole females during the 1992 and
1993 eastern Bering Sea trawl surveys have been used in this assessment for
the past 20 years (Table 4.10).  Nichol (1995) estimated the age of 50%
maturity at 10.5 years based on the histological examination of 639 ovaries. 
Maturity has recently been re-evaluated from a histological analysis of
ovaries collected in 2012 (Table 4.10). Results were very similar to the
earlier study with only a 2% difference in estimates of yellowfin sole female
spawning biomass (TenBrink and Wilderbuer 2015).  In addition, the SSC
requested that the assessment use a maturity schedule that uses estimates
derived from both the 1992 and the 2012 collections (Table 4.10). For
yellowfin sole sexual maturity occurs well after the age of entry into the
fishery.  Yellowfin sole females are 82% selected to the fishery by age 10
whereas they have been found to be only 40% mature at this age. 


#  Analytic approach
##  General model structure

The abundance, mortality, recruitment and selectivity of yellowfin sole were assessed with a stock assessment model using the AD Model Builder language (Fournier et al. 2012; Ianelli and Fournier 1998).  The conceptual model is a separable catch-age analysis that uses survey estimates of biomass and age composition as auxiliary information (Fournier and Archibald 1982).  The assessment model simulates the dynamics of the population and compares the expected values of the population characteristics to the characteristics observed from surveys and fishery sampling programs.  This is accomplished by the simultaneous estimation of the parameters in the model using the maximum likelihood estimation procedure.  The fit of the simulated values to the observable characteristics is optimized by maximizing a log(likelihood) function given some distributional assumptions about the observed data.  
The model starts at age one and fish older than twenty are allowed to accumulate into a plus group. Since the sex-specific weight-at-age for yellowfin sole diverges after age of maturity (about age 10 for 40% of the stock) with females growing larger than males, the current assessment model is coded to accommodate the sex-specific aspects of the population dynamics of yellowfin sole.  The model allows for the input of sex-specific estimates of fishery and survey age composition and weight-at-age and provides sex-specific estimates of population numbers, fishing mortality, selectivity, fishery and survey age composition and allows for the estimation of sex-specific natural mortality and catchability.  The model retains the utility to fit combined sex data inputs.
The suite of parameters estimated by the model are classified by three likelihood components:
Data component  Distributional assumption
Trawl fishery catch-at-age  Multinomial
Trawl survey population age composition Multinomial
Trawl survey biomass estimates and S.E. Log normal
The total log likelihood is the sum of the likelihoods for each data component (Table 4.11).  The likelihood components may be weighted by an emphasis factor, however, equal emphasis was placed on fitting each likelihood component in the yellowfin sole assessment except for the catch. The AD Model Builder software fits the data components using automatic differentiation (Griewank and Corliss 1991) software developed as a set of libraries (AUTODIFF C++ library).  Table 4.11 also presents the key equations used to model the yellowfin sole population dynamics in the Bering Sea and Table 4.12 provides a description of the variables used in Table 4.11.
Sharp increases in trawl survey abundance estimates for most species of Bering Sea flatfish between 1981 and 1982 indicate that the 83-112 trawl was more efficient for capturing these species than the 400-mesh eastern trawl used in 1975, and 1979-81.  Allowing the model to tune to these early survey estimates would most likely underestimate the true pre-1982 biomass, thus exaggerating the degree to which biomass increased during that period.  Although this underestimate would have little effect on the estimate of current yellowfin sole biomass, it would affect the spawner and recruitment estimates for the time-series.  Hence, the pre-1982 survey biomass estimates were omitted from the analysis.
The model of yellowfin sole population dynamics was evaluated with respect to the observations of the time-series of survey and fishery age compositions and the survey biomass trend since 1982. 
Parameters Estimated Outside the Assessment Model
Natural mortality (M) was initially estimated by a least squares analysis where catch at age data were fitted to Japanese pair trawl effort data while varying the catchability coefficient (q) and M simultaneously.  The best fit to the data (the point where the residual variance was minimized) occurred at a M value of 0.12 (Bakkala and Wespestad 1984).  This was also the value which provided the best fit to the observable population characteristics when M was profiled over a range of values in the stock assessment model using data up to 1992 (Wilderbuer 1992).  Since then, natural mortality has been estimated as a free parameter in some of the stock assessment model runs which have been evaluated the past five years.  A natural mortality value of 0.12 is used for both sexes in the base model presented in this assessment.
Yellowfin sole maturity schedules were estimated from in-situ observations from two studies as discussed in a previous section (Table 4.10).
Parameters Estimated Inside the Assessment Model
The parameters estimated by the model are presented below:
Fishing 
mortality Selectivity Survey 
catchability  Year class 
strength  Spawner-
recruit Total
66  268 4 105 2 445

The increase in the number of parameters estimated in this assessment compared to last year (8) can be accounted for by the input of another year of fishery data and the entry of another year class into the observed population, four more sex-specific fishery selectivity parameters and 2 additional catchability parameters.
Year Class Strengths
The population simulation specifies the numbers-at-age in the beginning year of the simulation, the number of recruits in each subsequent year, and the survival rate for each cohort as it moves through the population over time using the population dynamics equations given in Table 4.11.
Selectivity
Fishery and survey selectivity was modeled separately for males and females using the two parameter formulation of the logistic function (Table 4.11).  The model was run with an asymptotic selectivity curve for the older fish in the fishery and survey, but still was allowed to estimate the shape of the logistic curve for young fish.  The oldest year classes in the surveys and fisheries were truncated at 20 and allowed to accumulate into the age category 20+ years.  A single selectivity curve, for both males and females, was fit for all years of survey data.
Given that there have been annual changes in management, vessel participation and most likely gear selectivity, time-varying fishing selectivity curves were estimated. A logistic equation was used to model fishery selectivity and is a function of time-varying parameters specifying the age and slope at 50% selection,  and  , respectively.  The fishing selectivity (Sf) for age a and year t is modeled as, 
 
where ηt and φt are time-varying and partitioned (for estimation) into parameters representing the mean and a vector of deviations (log-scale) conditioned to sum to zero.  The deviations are constrained by a lognormal prior with a variance that was iteratively estimated.  The process of iterating was to first set the variance to a high value (diffuse prior) of 0.52 and estimate the deviations.  The next step was to compare the variability of model estimates.  The variance of the model estimates were then rounded up slightly and fixed for subsequent runs.  The 2016 values were fixed as the average of the 3 most recent years.
Fishing Mortality
The fishing mortality rates (F) for each age and year are calculated to approximate the catch weight by solving for F while still allowing for observation error in catch measurement.  A large emphasis (300) was placed on the catch likelihood component to force the model to closely match the observed catch.
Survey Catchability
A past assessment (Wilderbuer and Nichol 2001) first examined the relationship between estimates of survey biomass and bottom water temperature.  To better understand how water temperature may affect the catchability of yellowfin sole to the survey trawl, catchability was estimated for each year in the stock assessment model as:
 
where q is catchability, T is the average annual bottom water temperature anomaly at survey stations less than 100 m, and α and β are parameters estimated by the model.  The catchability equation has two parts.  The e -α term is a constant or time-independent estimate of q. The second term, eβT  is a time-varying (annual) q which responds to metabolic aspects of herding or distribution (availability) which can vary annually with bottom water temperature.  The result of incorporating bottom temperature to estimate annual q has resulted in an improved fit to the survey (shown in Figure 4.12 for the base model).  
In this assessment we introduce a revised survey catchability model (Model 18_1) where survey start date (expressed as deviation in days (- and +) from the average survey start date of June 4th) and it’s interaction with annual bottom water temperature is added to the catchability equation as:
q=e-α+βT+γS+µT:S
where T=survey bottom temperature (averaged per year for all stations <100 m), S=survey start date, and T:S=interaction of T and S.  Earlier survey start dates usually encounter colder water and since the timing of the survey start date is positively correlated with bottom water temperature, improvement in fitting the survey biomass estimates can be gained by estimating two new parameters (µ and ɤ).  Akaike information criterion (AIC) were used to determine if the additional variables (S and T:S) improved the regression fit.  The improvement in fit was more than offset by the additional two parameters (Nichol et al. In review).
Spawner-Recruit Estimation
Annual recruitment estimates from 1978-2012 were constrained to fit a Ricker (1958) form of the stock recruitment relationship as follows:
 
where R is age 1 recruitment, S is female spawning biomass (t) the previous year, and α and β are parameters estimated by the model.  The spawner-recruit fitting is estimated in a later phase after initial estimates of survival, numbers-at-age and selectivity are obtained.


# Results
## Model evaluation


## Time series results
## Recruitment

## Retrospective analysis

# Harvest recommendations
## Status summary





## Amendment 56 Reference Points



## Specification of OFL and Maximum Permissible ABC



## Standard Harvest Scenarios and Projection Methodology
<!--

Five of the seven standard scenarios will be used in an Environmental
Assessment prepared in conjunction with the final SAFE. These five scenarios,
which are designed to provide a range of harvest alternatives that are likely
to bracket the final TAC for 2018, are as follows (“$maxFABC$” refers to the
maximum permissible value of FABC under Amendment 56):

\begin{description}
\item[Scenario 1:]   
In all future years, $F$ is set equal to max$F_{ABC}$. (Rationale:  Historically,
TAC has been constrained by ABC, so this scenario provides a likely upper
limit on future TACs).

\item[Scenario 2:]   
In `r nextyr; print("and"); nextyr+1` the catch is set equal to 1.35 million t
and in future years $F$ is set equal to the Tier 3 estimate (Rationale: this was
has been about equal to the catch level in recent years).

\item[Scenario 3:]   
In all future years, $F$ is set equal to the `r thisyr-6;print("-");thisyr-1` average $F$. (Rationale:
For some stocks, TAC can be well below ABC, and recent average $F$ may provide a
better indicator of $F_{TAC}$ than $F_{ABC}$.)

\item[Scenario 4:]   
Scenario 4: In all future years, $F$ is set equal to $F_{60\%}$. (Rationale:  This
scenario provides a likely lower bound on $F_{ABC}$ that still allows future
harvest rates to be adjusted downward when stocks fall below reference levels.

\item[Scenario 5:]   
Scenario 5: In all future years, $F$ is set equal to zero. (Rationale:  In
extreme cases, TAC may be set at a level close to zero.)

\item[Scenario 6:]   
In all future years, F is set equal to $F_{OFL}$. (Rationale:  This scenario
determines whether a stock is overfished. If the stock is expected to be 
1) below its MSY level in `r thisyr` or 2) below half of its MSY level in `r thisyr` or below
its MSY level in `r thisyr +10` under this scenario, then the stock is overfished.)

\item[Scenario 7:]   
In `r nextyr` and `r nextyr+1`, F is set equal to $maxFABC$, and in all subsequent years, F
is set equal to $F_{OFL}$. (Rationale:  This scenario determines whether a stock is
approaching an overfished condition. If the stock is 1) below its MSY level in
`r nextyr+1` or 2) below 1/2 of its MSY level in `r nextyr+1` and expected to be below its MSY
level in `r thisyr+12` under this scenario, then the stock is approaching an
overfished condition).

\end{description}

The latter two scenarios are needed to satisfy the MSFCMA’s requirement to
determine whether a stock is currently in an overfished condition or is
approaching an overfished condition (for Tier 3 stocks, the MSY level is
defined as $B_{35\%}$).
-->

## Projections and status determination 

<!--
For the purposes of these projections, we present results based on selecting
the $F_{40\%}$ harvest rate as the $F_{ABC}$ value and use $F_{35\%}$ as a
proxy for $F_{MSY}$. Scenarios 1 through 7 were projected 14 years from 
`r thisyr` (Tables \ref{tab:tier3_C} through \ref{tab:tier3_SSB}). Under the
catch set to Tier 3 ABC estimates, the expected spawning biomass will
decline until 2020 and stabilize slightly above $B_{40\%}$ (in expectation,
Fig. \ref{fig:tier3_proj}).

Any stock that is below its minimum stock size threshold (MSST) is defined to
be overfished. Any stock that is expected to fall below its MSST in the next
two years is defined to be approaching an overfished condition. Harvest
scenarios 6 and 7 are used in these determinations as follows:

Is the stock overfished? This depends on the stock’s estimated spawning
biomass in `r thisyr`:

* If spawning biomass for `r thisyr ` is estimated to be below 1/2 $B_{35\%}$ the stock is below its MSST.   

* If spawning biomass for `r thisyr ` is estimated to be above $B_{35\%}$, the stock is above its MSST.   

* If spawning biomass for `r thisyr` is estimated to be above 1/2 $B_{35\%}$ but below $B_{35\%}$,
 the stock’s status relative to MSST is determined by referring to harvest
 scenario 6 ((Tables \ref{tab:tier3_C} through \ref{tab:tier3_SSB}). If the mean spawning biomass for
 `r thisyr + 10` is below $B_{35\%}$, the stock is below its MSST. Otherwise, the stock is
 above its MSST.

Is the stock approaching an overfished condition?  This is determined by
referring to harvest Scenario 7:

* If the mean spawning biomass for 2018 is below 1/2 $B_{35\%}$, the stock is approaching an overfished condition.  

* If the mean spawning biomass for 2018 is above $B_{35\%}$, the stock is not approaching an overfished condition.  

* If the mean spawning biomass for `r nextyr+1` is above 1/2 $B_{35\%}$ but below $B_{35\%}$, the
  determination depends on the mean spawning biomass for 2028. If the mean
  spawning biomass for `r nextyr+11` is below $B_{35\%}$, the stock is approaching an
  overfished condition. Otherwise, the stock is not approaching an overfished
  condition.

For scenarios 6 and 7, we conclude that pollock is above MSST for the year 
`r thisyr`,  and it is expected to be above the "overfished condition" based on
Scenario 7 (the mean spawning biomass in `r thisyr` is above the $B_{35\%}$
estimate; (Table \ref{tab:tier3_SSB}). Based on this, the EBS pollock stock is
being fished below the overfishing level and the stock size is estimated to be
above, abd stay above the overfished level.
-->

## ABC Recommendation
<!--
ABC levels are affected by estimates of $F_{MSY}$ which depends principally on
the estimated stock-recruitment steepness parameter, demographic schedules
such as selectivity-at-age, maturity, and growth. The current stock size (both
spawning and fishable) is estimated to be  at above-average levels and
projections indicate declines.  Updated data and analysis result in an
estimate of `r thisyr` spawning biomass (`r M$curssbs` kt) which is about 
`r round(100*M$curssb/M$bmsy,0)`\% of $B_{MSY}$ (`r M$bmsys` kt). The replacement
yield---defined as the catch next year that is expected to achieve a `r nextyr`
spawning biomass estimate equal to that from `r thisyr`---is estimated to be about
`r M$repl_ylds` t. Note that the negative value for replacement yield suggests that the
stock will decline even in the absence of any fishing. This follows a period of increases from 2008--2017 and
is expected. The extent that the stock will exhibit declines into the future depends 
on future recruitment, which is always uncertain. Some issues to consider in 
the medium-term are that

1.  The conditions in summer 2018 were exceptional in the complete absence of a "cold pool" and being a second consecutive 
    year with significant abundances found outside of the standard survey area.

2.  There were relatively few juvenile pollock observed in the surveys during the 
summers of 2016--2018.

3.  The recent BTS data continue to show low abundances of pollock aged 10 and older (Table \ref{tab:bts_age}).
Historically there had been good representation of older fish in data from
this survey. This is somewhat expected given the poor year-classes observed
during the period 2000--2005.

5.  The multispecies model suggests that the $B_{MSY}$ level is around 2.9 million
t instead of the  `r round(M$bmsy/1000,1)` million t estimated in the current assessment (noting that
the total natural mortality is higher in the multispecies model).

9.  Pollock are an important prey species for other species in the ecosystem and apparent changes in the 
    distribution may shift their availability as prey. 

11. Finally, given the same estimated aggregate fishing effort in 2018, the estimated stock trend is
    downwards except at low catch levels (a replacement yield of `r M$repl_ylds` kt is the amount that would
    maintain the spawning stock constant). Being a negative value means that even without any fishing,the stock
    is projected to decline. Furthermore, the ability to catch roughly the same amount as in `r thisyr` 
    through to 2022 will require about *75\% more effort* (effectively) with a decline in spawning biomass of about 30\% compared to
    the current level (based on expected average recruitment; Fig. \ref{fig:proj_const_catch}).  
-->

### Should the ABC be reduced below the maximum permissible ABC? 
<!--
The SSC in its September 2018 minutes recommended that assessment authors and
plan teams use the risk matrix table below when determining whether to
recommend an ABC lower than the maximum permissible. This was implemented for this year's recommendation. 

\clearpage

\begin{table}[ht]
\scalebox{0.88}{
\begin{tabular}{C{0.7in}L{2.0in}L{2.0in}L{2.0in}}
\hline
 &\multicolumn{3}{c}{\textbf{Considerations}} \\
\hline
 &\textbf{Assessment-related} & \textbf{ Population dynamics} & \textbf{Environmental \& ecosystem }     \\
\hline
Level 1 Normal                           & Typical to moderately increased uncertainty \& minor unresolved issues in assessment               & Stock trends are typical for the stock; recent recruitment is within normal range.                                                      & No apparent environmental \& ecosystem concerns                                                                                                                      \\
Level 2 Substantially increased concerns & Substantially increased assessment uncertainty unresolved issues.                                       & Stock trends are unusual; abundance increasing or decreasing faster than has been seen recently, or recruitment pattern is atypical.             & Some indicators showing an adverse signals but the pattern is inconsistent across all indicators.                                                            \\
Level 3 Major Concern                    & Major problems with the stock assessment, very poor fits to data, high level of uncertainty, strong retrospective bias. & Stock trends are highly unusual; very rapid changes in stock abundance, or highly atypical recruitment patterns.                           & Multiple indicators showing consistent adverse signals a) across the same trophic level, and/or b) up or down trophic levels (i.e., predators and prey of stock) \\
Level 4 Extreme concern                  & Severe problems with the stock assessment, severe retrospective bias. Assessment considered unreliable.          & Stock trends are unprecedented. More rapid changes in stock abundance than have ever been seen previously, or a very long stretch of poor recruitment compared to previous patterns. & Extreme anomalies in multiple ecosystem indicators that are highly likely to impact the stock. Potential for cascading effects on other ecosystem components    \\
\hline
\end{tabular}
}
\end{table}

The table is applied by evaluating the severity of three types of
considerations that could be used to support a scientific recommendation to
reduce the ABC from the maximum permissible. Examples of the types of concerns that
might be relevant include the following (as identified by the work-group):  

  1. Assessment considerations  
    -  _Data-inputs:_ biased ages, skipped surveys, lack of fishery-independent trend data  
    -  _Model fits:_ poor fits to fits to fishery or survey data, inability to simultaneously fit multiple data inputs.  
    -  _Model performance:_ poor model convergence, multiple minima in the likelihood surface, parameters hitting bounds.  
    -  _Estimation uncertainty:_ poorly-estimated but influential year classes.  
    -  Retrospective bias in biomass estimates.  

  2. Population dynamics considerations—decreasing biomass trend, poor recent
  recruitment, inability of the stock to rebuild, abrupt increase or decrease
  in stock abundance.  
  
  3. Environmental/ecosystem considerations—adverse trends in
  environmental/ecosystem indicators, ecosystem model results, decreases in
  ecosystem productivity, decreases in prey abundance or availability,
  increases or increases in predator abundance or productivity.  

*Assessment considerations*   The EBS pollock assessment model appears to
track the  stock from year based on retrospective analysis (the pattern lacks
tendency to over or under estimate the stock trend. The model tracks the
available data well including  multiple abundance indices. Of minor concern
(presently) is the fact that the model estimate of declining abundance is
somewhat less than that suggested by the survey data. The data and model
appear to be consistent without big surprises relative to the ability to fit
the information and provide a trade-off between process and observation errors
(which combined, provide relatively high estimates of uncertainty). **We
therefore rated the assessment-related concern as level 1, normal.**

*Population dynamics considerations*  The age structure of EBS pollock  has
exhibited some peculiarities over time. On the positive side, some strong
year-classes appear to have increased in abundance based on the bottom-trawl
survey data (e.g., the 1992 and 2012 year classes). Conversely, the period
from 2000--2007 had relatively poor year-class strengths which resulted in
declines in stock below $\it{B_{msy}}$ and reduced TACs due to lower ABC
values. There also are clear density-dependent effects on growth, in
particular, the 2012 year class. The stock is estimated to be well above
$\it{B_{msy}}$ at present, but projections indicate a decline given recent
catch levels and future trends will depend on pollock survival at egg, larval,
and juvenile stages which may be compromised given the lack of a cold pool and
a  considerable redistribution into the northern part of the Bering Sea. It
seems likely that recruitment in the near term will be below average yet the
population dynamics, being data driven, projects recruitment to be average.
Additional age-specific aspects of the spawning population indicates that the
stock is at a low diversity of ages and the mean age of the spawning stock
(weighted by spawning output) are both at relatively low levels (Fig.
\ref{fig:age_diversity}). **We therefore rated the population-dynamic concern as
level 2, a substantially increased concern.**

*Environmental/Ecosystem considerations*
2018 was unprecedented (for the period of our observations) with near-
complete lack of sea ice in the Northern Bering Sea and complete lack of sea
ice (and resulting cold pool) over the southeastern Bering Sea shelf. The
ecosystem responses indicate potential concerns for pollock, as both prey
resources and predator dynamics were impacted. Over the southern shelf, a
weak, delayed bloom provided reduced phytoplankton biomass which likely
impacted the zooplankton prey base.

Small copepod production in the spring of 2018 was apparently above average,
but decreased nauplii survival is predicted based on reduced phytoplankton.
Both acoustic and RZA (rapid zooplankton assessment) estimates indicate low
euphausiid abundance; both indicators suggest this high-quality prey has
become less available since 2012. Over the northern shelf, large copepods were
an order of magnitude less abundant than a previous survey conducted in 2007;
euphausiids were also several orders of magnitude lower. Larval pollock
production appears high (comparable to 2014 and 2016), which is expected in
warm years, but larval survival is expected to be low due to degraded prey
resources and reduced energy transfer.

Fish condition (based on weight/length residuals) show that adult pollock
condition was negative in both the SEBS and NBS, which continues a declining
trend since 2012. The biomass of the pelagic forager guild, which includes
pollock, remains below the long-term mean with pollock declining 59\%
since 2014 and 38\% since 2017. Total CPUE of groundfish estimated from the
bottom trawl survey showed a sharp decline in 2018, primarily due to a
decrease in pollock,  Pacific cod, and several flatfish species.

A seabird die-off event, unprecedented in terms of spatial and temporal scale,
combined with broad reproductive failures and/or late breeding success
indicate, in part, a lack of sufficient prey resources (emaciation and
starvation are the only identified causes of mortality to date). 
In addition to several of these species preying on juvenile pollock, 
they also rely on the same zooplankton as pollock for survival. The die-offs
may be indicative of poor juvenile pollock survival and/or available prey for
juvenile pollock. Some outstanding ecosystem questions are whether
 Pacific cod and pollock remained in the NBS over winter 2017--2018.
 Given the warm water temperatures (and lack of sea
ice), over-winter feeding to meet their metabolic demands may
have reduced the prey base and shifted the food-web balance in the
NBS.

There were also unusual observations of adult pollock behavior in Bristol Bay
and these may be indicative of (i) a distribution shift in response to warm
temperatures (although temperatures SEBS shelf were similar to a ‘typical’
warm year), (ii) looking for adequate prey (although stomachs were not empty
and contents were ‘typical’), or (iii) potential harmful algal bloom event (samples still
being processed). 

In summary, 

  - Unprecedented warm conditions in 2018 resulted in reduced primary and secondary production        

  - The cold pool prediction for summer 2019 is for continued warm conditions and reduced cold pool extent        

  - Weak, delayed phytoplankton bloom, reduced biomass, and reduced energy transfer to upper trophic levels (i.e., zooplankton prey base and juvenile pollock)        

  - Zooplankton prey base reduced (small, lipid-poor taxa, few euphausiids)        

  - Adult pollock condition index is negative in both SEBS and NBS and has been trending downwards in SEBS since 2010.        

  - Unprecedented seabird die-off event and broad reproductive failures indicate, in part, a lack of sufficient prey resources        

**We therefore rated the Ecosystem concern as Level 2, substantially increased concern.**
These results are summarized as:
\begin{table}[h]
\begin{tabular}{L{1.5in}L{1.5in}L{1.5in}L{1.5in}}
\hline
 \multicolumn{3}{c}{Considerations}  & \\
Assessment-related & Population dynamics & Environmental or ecosystem & Score (max of individual) \\
\hline
Level 1: No concern               & Level 2: Substantially increased concerns & Level 2: Substantially increased concerns & Level 2: Substantially increased concerns       \\
\hline
\end{tabular}
\end{table}

The overall score is level 2, the maximum of the individual scores, suggests
that setting an ABC below the maximum permissible is warranted. The SSC
recommended against using a table that showed example alternatives to select
buffers based on that risk level. Thompson (unpublished Sept 2018 plan team
document) tabulated the magnitude of buffers applied by the Plan Teams for the
period 2003--2017, and found that the mode of the buffers recommended was 10--20\%.
 Using this as a guideline, a buffer of 15\% would give an ABC as
$0.85 \times \text{ABC}_{max}$ = `r formatC(M$maxabc1*0.850,big.mark=",",digits=0,format="d")` kt).
In the past, the SSC has considered factors similar to those presented above 
and selected an ABC based on Tier 3 estimates. We recommend this added precaution again 
again this year, (i.e., ABC = `r formatC(M$Tier3_ABC1,big.mark=",",digits=0,format="d")` kt) 
which implies a buffer of  `r round(100*(1-M$Tier3_ABC1/M$maxabc1),0)`\%.  

Recognizing that the actual catch will be constrained by other factors (the 2 million t BSAI
groundfish catch limit and bycatch avoidance measures),  applying the maximum
permissible Tier 1a ABC seems clearly risky. Such high catches would result in
unprecedented variability and removals from the stock (and require
considerably more capacity and effort). Less variability in catch  would also
result in less spawning stock variability (and reduce risks to the fishery
should another period of poor recruitments occur).  To more fully evaluate these
considerations performance indicators as modified from Ianelli et al. (2012)
were developed to evaluate some near-term risks given  alternative 2019 catch
values.  These indicators and rationale for including them are summarized in
Table \ref{tab:dec_tab_rationale}).   Model 16.1 results for these indicators
are provided in  Table \ref{tab:dec_table}. Each column of this table uses a
fixed 2019 catch and assumes the same effort  for the four additional
projection years (2020--2023).  Given this specification , there is a low
probability that any of the catches   shown in the first row would exceed the
$F_{MSY}$ level.  Also, in the near term it appears unlikely that the spawning
stock will be below $B_{MSY}$ (rows 3 and 4).  Relative to the historical mean
spawning biomass, by 2020 it is more likely than not that the spawning biomass
will be lower than the historical mean (fifth row). The range of catches
examined have relatively small or no impact on  the age diversity indicators.
However, for catch to equal the 2018 value, more fishing effort will likely be
required and there is an good chance that the proportion of the stock less
than age 6 will be greater than the historical average. In terms of catch
advice, aiming for  a catch between 1.25 and 1.374 million t results in a
roughly even chance that the stock in  2020 will be equal to the long term mean.
-->
  
# Ecosystem considerations

In general, a number of key issues for ecosystem conservation and management can be highlighted. These include:    

  * Preventing overfishing;    

  * Avoiding habitat degradation;    

  * Minimizing incidental bycatch;    

  * Monitoring bycatch and the level of discards; and    

  * Considering multi-species trophic interactions relative to harvest policies.    

For the case of pollock in the Eastern Bering Sea, the NPFMC and NMFS continue
to manage the fishery on the basis of these issues in addition to the single-
species harvest approach (Hollowed et al. 2011). The prevention of overfishing
is clearly set out as the main guideline for management. Habitat degradation
has been minimized in the pollock fishery by converting the industry to
pelagic-gear only. Bycatch in the pollock fleet is closely monitored by the
NMFS observer program and managed on that basis. Discard rates of many species
have been reduced in this fishery and efforts to minimize bycatch continue.

In comparisons of the Western Bering Sea (WBS) with the Eastern Bering Sea
using mass-balance food-web models based on 1980--85 summer diet data, Aydin et
al. (2002) found that the production in these two systems is quite different.
On a per-unit-area measure, the western Bering Sea has higher productivity
than the EBS. Also, the pathways of this productivity are different with much
of the energy flowing through epifaunal species (e.g., sea urchins and
brittlestars) in the WBS whereas for the EBS, crab and flatfish species play a
similar role. In both regions, the keystone species in 1980--85 were pollock
and Pacific cod. This study showed that the food web estimated for the EBS
ecosystem appears to be relatively mature due to the large number of
interconnections among species. In a more recent study based on 1990--93 diet
data (see Appendix 1 of the Ecosystem Considerations chapter for methods),
pollock remain in a central role in the ecosystem. The diet of pollock is
similar between adults and juveniles with the exception that adults become
more piscivorous (with consumption of pollock by adult pollock representing
their third largest prey item).

Regarding specific small-scale ecosystems of the EBS, Ciannelli et al. (2004a,
2004b) presented an application of an ecosystem model scaled to data available
around the Pribilof Islands region. They applied bioenergetics and foraging
theory to characterize the spatial extent of this ecosystem. They compared
energy balance, from a food web model relevant to the foraging range of
northern fur seals and found that a range of 100 nautical mile radius encloses
the area of highest energy balance representing about 50% of the observed
foraging range for lactating fur seals. This has led to a hypothesis that fur
seals depend on areas outside the energetic balance region. This study
develops a method for evaluating the shape and extent of a key ecosystem in
the EBS (i.e., the Pribilof Islands). Furthermore, the overlap of the pollock
fishery and northern fur seal foraging habitat (see Sterling and Ream 2004,
Zeppelin and Ream 2006) will require careful monitoring and evaluation.
<!--

A brief summary of these two perspectives (ecosystem effects on pollock stock
and pollock fishery effects on ecosystem) is given in (Table \ref{tab:pscbycatch}). Unlike the
food-web models discussed above, examining predators and prey in isolation may
overly simplify relationships. This table serves to highlight the main
connections and the status of our understanding or lack thereof.
-->


## Ecosystem effects on the EBS pollock stock 
<!--
The pollock stock condition appears to have benefited substantially from the
recent conditions in the EBS. The conditions on the shelf during 2008
apparently affected age-0 northern rock sole due to cold
conditions and apparently unfavorable currents that retain them into the over-
summer nursery areas (Cooper et al. 2014). It may be that such conditions
favor pollock recruitment. Hollowed et al. (2012) provided an extensive review
of habitat and density for age-0 and age-1 pollock based on survey
data. They noted that during cold years, age-0 pollock were distributed
primarily in the outer domain in waters greater than 1$^\circ$C and during warm
years, age-0 pollock were distributed mostly in the middle domain. This
temperature relationship, along with interactions with available food in
early-life stages, appears to have important implications for pollock
recruitment success (Coyle et al. 2011). The fact that the 2012 year-class
appears to be strong, as it ages that contribution to the stock will 
diminish.

A separate section presented again this year updates a multispecies model with
more recent data and is presented as a supplement to the BSAI SAFE report. In
this approach, a number of simplifications for the individual species data and
fisheries processes (e.g., constant fishery selectivity and the use of
design-based survey indices for biomass). However, that model mimics the
biomass levels and trends with the single species reasonably well. It also
allows specific questions to be addressed regarding pollock TACs. For example,
since predation (and cannibalism) is explicitly modeled, the impact of
relative stock sizes on subsequent recruitment to the fishery can be now be
directly estimated and evaluated (in the model presented here, cannibalism is
explicitly accounted for in the assumed Ricker stock-recruit relationship).


Euphausiids make up a large component of the pollock diet. The euphausiid abundance on the
Bering Sea shelf is presented as a section of the 2017 Ecosystem
Considerations Chapter of the SAFE report and shows a continued decline in
abundance since the peak in 2009 (for details see De Robertis et al. (2010) and
Ressler et al. (2012). The role that the apparent recent 2009 peak abundance
had in the survival of the 2008 year class of EBS pollock is interesting.
Contrasting this with how the feeding ecology of the 2012 year class (also
apparently well above average) may differ is something to evaluate in the
future.
-->

## EBS pollock fishery effects on the ecosystem. 
<!--

Since the pollock fishery is primarily pelagic in nature, the bycatch of non-
target species is small relative to the magnitude of the fishery 
(Table \ref{tab:nontargbycatch}).
Jellyfish represent the largest component of the bycatch of non-target species
and had averaged around 5--6 kt per year but more than doubled in
2014 but has dropped in 2015 and been about average since then. The data on non-target species shows a high
degree of inter-annual variability, which reflects the spatial variability of
the fishery and high observation error. This variability may reduce the
ability to detect significant trends for bycatch species.

The catch of other target species in the pollock fishery (defined as any trawl 
set where the catch represents more than 80% of the catch) represents less than
1% of the total pollock catch. Incidental catch of Pacific cod has varied
but in the past three years it is about half of the 2011 and 2012 levels (Table \ref{tab:fmpbycatch}). 
There has been a marked in increase in the incidental
catch of Pacific ocean perch, sablefish, and Atka mackerel and a
decrease in flatfish species.
Proportionately, the incidental catch decreased since the
overall levels of pollock catch have increased since 2008. In fact, the bycatch of
pollock in other target fisheries is more than double the bycatch of target
species in the pollock fishery (Table \ref{tab:pollbycatch}).

The number of non-Chinook salmon (nearly all made up of chum salmon) taken
incidentally has steadily increased since 2014 with 2017 number in excess of
465 thousand fish but the 2018 level was slightly more than the
2003--2017 average of 227 thousand fish; Table \ref{tab:pscbycatch}). Chinook
salmon bycatch has also increased steadily since 2012 with the 2017 counts at
just below 30,000 (which was 18% below the 2003--2017 mean value). In 2018 the
bycatch  dropped back down to 13.5 thousand fish  (Table
\ref{tab:pscbycatch}).  Ianelli and Stram (2014) provided estimates of the
bycatch impact on Chinook salmon runs to the coastal west Alaska region and
found that the peak bycatch levels exceeded 7% of the total run return. Since
2011, the impact has been estimated to be below 2%. Updated estimates  given
new genetic information and these levels of PSC were provided to the
Council in 2018 and impact levels remain low.


-->
# Data gaps and research priorities


# Acknowledgements

